framework:
    mailer:
        dsn: "%env(MAILER_DSN)%"
        envelope:
            sender: 'postmaster@ducktales.com'
        headers:
            from: "DuckTales Postmaster <postmaster@ducktales.com>"
