version: "3.7"

services:
  # ElasticSearch Server
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"

  # GUI
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200/"
    ports:
      - 5601:5601